Get all flashes
zendframework/zend-expressive-flash pull request #6
Opened 2018-01-27 08:21 UTC by xtreamwayz

- [x] Are you creating a new feature?
  - [x] Why is the new feature needed? What purpose does it serve?
  - [x] Base your feature on the `develop` branch, and submit against that branch.
  - [x] Add only one feature per pull request; split multiple features over multiple pull requests
  - [x] Add tests for the new feature.
  - [x] Add documentation for the new feature.

Sometimes you don't which messages are added. `FlashMessages::getFlashes()` retrieves an array with all messages for the current request.

2018-01-27 10:00 UTC, michalbundyra requested changes

2018-01-27 10:00 UTC, webimpress commented on docs/book/messages.md
> +     * @return mixed
`mixed` or `array` ? or `mixed[]`?

2018-01-27 10:00 UTC, webimpress commented on docs/book/messages.md
> +     * @param mixed $default Default value to return if no flash value exists.
Can't see any param defined in the function signature.

2018-01-27 10:00 UTC, webimpress commented on docs/book/messages.md
> +     * Retrieve all flash values.
I'm not a big fan of copying code into the documentation, then we need to maintain it in two places, and always remember to update it in the docs.... I know it was already here and you've just updated it 👍

2018-01-27 10:00 UTC, webimpress commented on docs/book/messages.md
> +     * was called in this request with the same `$key`.
It is not clear what is the `$key`.

2018-01-27 10:00 UTC, webimpress commented on src/FlashMessages.php
> +     * @return mixed
The same comments here as in the docs

2018-01-27 10:00 UTC, webimpress commented on src/FlashMessagesInterface.php
> +     * @return mixed
And here as well.

2018-01-27 10:00 UTC, webimpress commented on test/TestAsset/FlashMessages.php
> +    }
This method definition is wrong, must return `array`, but it's `void`. Not sure where (if) it is used?

2018-01-27 12:15 UTC, michalbundyra approved these changes

2018-02-12 12:06 UTC, vitorloureiro commented
Hi @xtreamwayz 
It is possible to merge this? i think this is essential for the flash messages middleware.

2018-02-12 12:10 UTC, xtreamwayz commented
Yes, it's possible after a review from @weierophinney :)

2018-02-12 12:12 UTC, webimpress commented on src/FlashMessages.php
> +     * @return array
Can be removed, as we have it already in method signature.

2018-02-12 12:12 UTC, webimpress commented on src/FlashMessagesInterface.php
> +     * @return array
The same as above, can be removed.

2018-02-24 07:10 UTC, merged